initialize network with normal
cuda:6
================ (Mon Apr 18 09:04:16 2022) ================
gpu_ids: [6] project_name: auxilary_model_kmcuda_lam0.5_418 checkpoint_root: checkpoints num_workers: 4 dataset: CDDataset data_name: LEVIR batch_size: 16 split: train split_val: val img_size: 256 n_class: 2 output_sigmoid: False net_G: base_transformer_pos_s4_dd8_dedim8_outsigmoid loss: ce_aux optimizer: sgd lr: 0.005 max_epochs: 300 lr_policy: linear lr_decay_iters: 100 checkpoint_dir: checkpoints/auxilary_model_kmcuda_lam0.5_418 vis_dir: /archive/hot8/cd_data/BIT/vis/auxilary_model_kmcuda_lam0.5_418 loading last checkpoint...
Epoch_to_start = 1, Historical_best_acc = 0.0000 (at epoch 0)
lr: 0.0049834
Traceback (most recent call last):
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/main_cd.py", line 87, in <module>
    train(args)
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/main_cd.py", line 16, in train
    model.train_models()
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/models/trainer.py", line 283, in train_models
    self._backward_G()
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/models/trainer.py", line 259, in _backward_G
    self.G_loss = self._pxl_loss(self.G_pred, gt, self.device, weight=self.weight)
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/models/losses.py", line 32, in cross_entropy_with_auxilary
    aux = auxilary_loss(input, target, device)
  File "/home/tanrui@corp.sse.tongji.edu.cn/CD_algs/BIT/models/losses.py", line 53, in auxilary_loss
    return F.binary_cross_entropy(input=input2, target=label)
  File "/home/tanrui@corp.sse.tongji.edu.cn/.conda/envs/tanrui/lib/python3.6/site-packages/torch/nn/functional.py", line 2908, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([16, 256, 256])) that is different to the input size (torch.Size([16, 1, 256, 256])) is deprecated. Please ensure they have the same size.